### ISSUE TITLE
Angle sign

### ISSUE THREAD

**Issue by ceisenbach** [ccny-physics-sims/science-library#3]
In the simple vector.
The angle displayed has the wrong sign, i.e. a negative sign instead of a positive one.

**Comment by hedbergj** [comment]
Yeah - I think there is a discrepancy between 'physics&math' angles which are CCW positive, and 'javascript' angles, which are positive going clockwise. Not sure which convention to adopt here. 
(eg: http://p5js.org/reference/#/p5/rotate )

**Comment by aareman** [comment]
I would stick with regular math convention. That way it is most intuitive to people looking at it. For the few programmer's that may be confused (they probably wont) we can just include it in the documentation.
